### ISSUE TITLE
Unable to parse `secretKey` for preloaded contracts

### ISSUE THREAD

**Issue by barnabasbusa** [paradigmxyz/reth#11611]
### Describe the bug

Reth crashes with error:
```sh
error: Invalid value '/network-configs/genesis.json' for --chain <CHAIN_OR_PATH>: invalid string length at line 922 column 23.
    [possible values: mainnet,sepolia,holesky,dev]%
``` 
when an "incorrect" field is defined.

### Steps to reproduce

Kurtosis run for this config:

```yaml
participants:
  - el_type: geth
  - el_type: reth
network_params:
  preset: minimal
  genesis_delay: 5
  additional_preloaded_contracts: '{
                    "0x4e59b44847b379578588920cA78FbF26c0B4956C": {
                        "balance": "0ETH",
                        "code": "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
                        "storage": {},
                        "nonce": "1",
                        "secretKey": "0x"
                    }
                }'
```

Every other EL client accepts `secretKey` field `"0x"`. Therefore I assume it is a bug in reth. 

If you remove the secretKey field completely, it works with reth. 

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

v1.0.8

### What database version are you on?

n/a

### Which chain / network are you on?

kurtosis

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct
