### ISSUE TITLE
Op-reth fails to build blocks with Ishtmus enabled

### ISSUE THREAD

**Issue by ferranbt** [paradigmxyz/reth#15435]
### Describe the bug

Op-reth fails to create blocks with Ishtmus enabled with this error:

![Image](https://github.com/user-attachments/assets/46623b9c-db6f-4710-8ff4-a84afcc5374e)

### Steps to reproduce

Run this Kurtosis script:
```
optimism_package:
  observability:
    enabled: true
  chains:
    - participants:
        - el_type: op-reth
      network_params:
        network: "kurtosis"
        fund_dev_accounts: true
        seconds_per_slot: 2
        fjord_time_offset: 0
        granite_time_offset: 0
        isthmus_time_offset: 0
ethereum_package:
  participants:
    - el_type: geth
      cl_type: teku
```

The same script works if I use op-geth instead.

### Node logs

```text
https://gist.github.com/ferranbt/99a0ba0f8892fd291f98e40bf972cd5d
```

### Platform(s)

Mac (Apple Silicon)

### Container Type

Docker

### What version/commit are you on?

sha256:c15a0fd315b606aeb90bce700383e40bd979f1168ef68b23095f2b32e3304111

### What database version are you on?

-

### Which chain / network are you on?

Kurtosis dev

### What type of node are you running?

Archive (default)

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by ferranbt** [comment]
![Image](https://github.com/user-attachments/assets/b92ef570-1fe5-4426-bffe-42810353843a)

I think Kurtosis was not pulling the latest version. I will try again.

**Comment by mattsse** [comment]
you can try the nightly image, we have released a patch since

**Comment by ferranbt** [comment]
I tried with nightly but I got a different error:

![Image](https://github.com/user-attachments/assets/f4fadde7-6054-4560-a0eb-85af6560df01)

The kurtosis config is:
```
optimism_package:
  observability:
    enabled: true
  chains:
    - participants:
        - el_type: op-reth
          el_image: "ghcr.io/paradigmxyz/op-reth:nightly"
      network_params:
        network: "kurtosis"
        fund_dev_accounts: true
        seconds_per_slot: 2
        fjord_time_offset: 0
        granite_time_offset: 0
        isthmus_time_offset: 0
ethereum_package:
  participants:
    - el_type: geth
      cl_type: teku
```
