### ISSUE TITLE
CPU spike after upgrading to v1.3.7

### ISSUE THREAD

**Issue by AntonieDavid** [paradigmxyz/reth#15653]
### Describe the bug

When upgrading from v1.3.4 to v1.3.7 on eth sepolia the nodes slowly reached 100% cpu usage (within an hour post-upgrade), when they eventually broke. first action was to downgrade back to v1.3.4, which resulted in stable behaviour until now. (incident happened on 4th of april)

### Steps to reproduce

run a reth archive node on eth sepolia network on v1.3.4 and bump the version straight to v1.3.7. 
the issue was observed mostly on not so performant servers -> either 8 or 12 cores with either 64 or 128 gb of ram. for example, the upgrade did not break a server with 16 cores and 128gb of ram.

### Node logs

```text
post-upgrade there were many logs like this:
reth[1425619]: 2025-04-04T13:53:57.929749Z  INFO State root task finished state_root=0xae1e5fb9966aefcd24e5a5fab137ed14ec1b8e2f013e9a48ba770533c10
be088 elapsed=156.781687ms

after a while, all the nodes started showing mostly this log:
reth[1425619]: 2025-04-04T13:58:02.431784Z  WARN Long-lived read transaction has been timed out open_duration=300.000078433s backtrace=None
```
### CPU chart

<img width="1409" alt="Image" src="https://github.com/user-attachments/assets/bb820f05-3fc1-49aa-8260-055cb99716c2" />

### Container Type

Not running in a container

### What version/commit are you on?

v1.3.7

### What database version are you on?

.

### Which chain / network are you on?

eth sepolia

### What type of node are you running?

Archive (default)

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
with 1.3.9 we introduced `--engine.max-proof-task-concurrency` that can be used to tune this, the default rn 256 but can be drastically decreased, suggesting to experiment with an appropriate value for this.

ideally we find a way to choose a better default depending on the machien

**Comment by johnsonco** [comment]
Hi there I'm having the same CPU spike issue. Running `Optimism` with op-reth (ghcr.io/paradigmxyz/op-reth:v1.3.12). I also used the snapshot from https://www.publicnode.com/snapshots#optimism.

The flags for op-geth and op-node:
```
      - name: op-reth
        image: ghcr.io/paradigmxyz/op-reth:v1.3.7
        args:
          - node
          - -vvv
          - --datadir=/data
          - --log.stdout.format=log-fmt
          - --log.file.directory=/logs
          - --http
          - --http.corsdomain="*"
          - --http.addr=0.0.0.0
          - --http.port=8545
          - --http.api=debug,eth,net,txpool
          - --authrpc.addr=0.0.0.0
          - --authrpc.port=8551
          - --authrpc.jwtsecret=/jwt.txt
          - --chain=optimism
          - --rollup.sequencer-http=https://mainnet-sequencer.optimism.io
          - --rollup.disable-tx-pool-gossip
          - --ipcpath=/data/reth.ipc

      - name: op-node
        image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.2
        args:
          - op-node
          - --l1=http://ethereum.ethereum.svc.cluster.local:8545
          - --l2=http://localhost:8551
          - --rpc.addr=127.0.0.1
          - --rpc.port=9545
          - --l2.jwt-secret=/jwt.txt
          - --l1.trustrpc
          - --l1.rpckind=basic
          - --l1.beacon=http://ethereum.ethereum.svc.cluster.local:5052
          - --syncmode=execution-layer
          - --network=op-mainnet
          - --rollup.load-protocol-versions=true
          - --rollup.halt=major
```

```
$ kubectl top pod -n optimism
NAME                     CPU(cores)   MEMORY(bytes)
optimism-0             60063m       11891Mi
optimism-1             60061m       12163Mi
optimism-2             60077m       12005Mi
optimism-3             60055m       12178Mi
optimism-4             60066m       12320Mi
```

Could you help and advise with this please?
