### ISSUE TITLE
Concurrent read of mdbx with docker fails 

### ISSUE THREAD

**Issue by awilper** [paradigmxyz/reth#2556]
### Describe the bug

Concurrent read of mdbx database fails with error 
```
../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
Aborted (core dumped)
```

The node is run with docker and the process attempting to concurrently read is also running in a docker container.

### Steps to reproduce

1. Launch a reth node with docker. I used the following docker compose since my nvme is mounted on /data 
```
version : '2.2'
services:
  reth:
    image: reth
    container_name: reth
    command: --db=/home/reth_chain --metrics "127.0.0.1:9000" --authrpc.jwtsecret=/home/reth_chain/jwt.hex
    volumes:
      - /data/reth_chain:/home/reth_chain

  lighthouse:
    image: sigp/lighthouse:v4.0.2-rc.0
    container_name: lighthouse
    command: lighthouse beacon --http --http-address=0.0.0.0 --http-allow-origin="*" --execution-jwt=/home/reth_cha
in/jwt.hex --execution-endpoint=http://reth:8551 --checkpoint-sync-url=https://beaconstate.info
    ports:
      - "9000:9000/tcp"
    volumes:
      - /data/lighthouse:/root/.lighthouse
      - /data/reth_chain:/home/reth_chain
 ```

2. Note another setup probably works, but this is the Dockerfile I used for the second processes. 

```# Rust base image
FROM rust:1.69 

RUN rustup target add x86_64-unknown-linux-musl

ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y tzdata gcc libffi-dev perl make git libprotobuf-dev python3-pip linux-perf
RUN apt-get install -y libclang-dev pkg-config
RUN rm /usr/bin/perf && ln /usr/bin/perf_5.10 /usr/bin/perf

ENV PROTOC /usr/local/bin/protoc

WORKDIR /app
```

4.  Run `docker run -it  -v ${PWD}:/app -v /data/reth_chain:/data/reth_chain revm /bin/bash` to enter the shell. The goal is to mount the code below in /app.

5.  Attempt db access. I'll post my haphazard file here for reproducibility, but there is surely an easier way to test db access. 
If you try to run this when reth is down, it'll succeed. 

```
use reth_provider::providers::BlockchainProvider;
use reth_provider::ShareableDatabase;
use reth_staged_sync::utils::init::init_db;

use reth_rpc::{eth::cache::EthStateCache, eth::EthTransactions, EthApi, EthFilter};
use reth_tasks::TokioTaskExecutor;
use reth_transaction_pool::EthTransactionValidator;

use reth_network_api::test_utils::NoopNetwork;

use reth_beacon_consensus::BeaconConsensus;
use reth_blockchain_tree::{
    config::BlockchainTreeConfig, externals::TreeExternals, BlockchainTree, ShareableBlockchainTree,
};
use reth_primitives::{H256, MAINNET};
use reth_revm::Factory;

use std::sync::Arc;

async fn attempt_access() {
    let db_path = "/data/reth_chain".to_string();
    println!("Opening db path {}", db_path);
    let db = Arc::new(init_db(db_path).unwrap());

    let chain = Arc::new((*MAINNET).clone());
    let consensus = Arc::new(BeaconConsensus::new(Arc::clone(&chain)));
    let tree_externals = TreeExternals::new(
        db.clone(),
        Arc::clone(&consensus),
        Factory::new(chain.clone()),
        Arc::clone(&chain),
    );
    let tree_config = BlockchainTreeConfig::default();
    let (canon_state_notification_sender, _receiver) =
        tokio::sync::broadcast::channel(tree_config.max_reorg_depth() as usize * 2);
    let blockchain_tree = ShareableBlockchainTree::new(
        BlockchainTree::new(tree_externals, canon_state_notification_sender, tree_config).unwrap(),
    );

    let shareable_db = ShareableDatabase::new(Arc::clone(&db), Arc::clone(&chain));
    let blockchain_db = BlockchainProvider::new(shareable_db, blockchain_tree);

    let transaction_pool = reth_transaction_pool::Pool::eth_pool(
        EthTransactionValidator::new(blockchain_db.clone(), Arc::clone(&chain)),
        Default::default(),
    );

    let eth_cache = EthStateCache::spawn_with(
        blockchain_db.clone(),
        Default::default(),
        TokioTaskExecutor::default(), // todo task executor
    ); 
    let _eth_filter = EthFilter::new(
        blockchain_db.clone(),
        transaction_pool.clone(),
        eth_cache.clone(),
    );
    let noop_network_provider = NoopNetwork::default();

    let eth_api = EthApi::new(
        blockchain_db.clone(),
        transaction_pool.clone(),
        noop_network_provider,
        eth_cache.clone(),
    );
    let txns_by_block = eth_api
        .transactions_by_block(
            "0x22e25546c3f3a90b3ac3bb92dbb916083f0e7004f23876f1d88a1cf766496261"
                .parse::<H256>()
                .unwrap(),
        )
        .await
        .unwrap();
    println!("response is {:?}", txns_by_block);
}

#[tokio::main]
async fn main() {
    attempt_access().await;
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

dfd35fa

### Code of Conduct

- [X] I agree to follow the Code of Conduct
