### ISSUE TITLE
Make pruning configurable via reth.toml

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3430]
### Describe the feature

We want to be able to configure pruning for different parts of the data stored in the database. It's not the same as configuring e.g. stage commit thresholds, because one stage can touch multiple tables. For example, `Execution` stage touches `Receipts`, `AccountChangeSet` and `StorageChangeSet` tables, which we may want to prune separately. 

So the config is not per stage, but per logical part of the data:
```toml
[prune]
block_interval = 5 # Check if pruning is required every 5 blocks

[prune.parts]
transaction_lookup = "full" # Prune "TxHashNumber" table fully
receipts = { distance = 10 } # Prune "Receipts" table, keeping last 10 blocks
account_history = { before = 17000000 } # Prune "AccountChangeSet" and "IndexAccountHistory" tables before 17 million blocks, leaving only 17 millionth and after
```
