### ISSUE TITLE
Storage History pruning by contract address or storage slot

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#4350]
### Describe the feature

Inspired by https://github.com/paradigmxyz/reth/issues/2753.

Basically, be able to prune `Storage History` part in a similar way as we can prune receipts by specifying the log addresses, but instead by specifying the contract address or storage slot.

**Comment by alessandromazza98** [comment]
I could try this one

**Comment by alessandromazza98** [comment]
A question: filtering by storage slot you mean filtering both with a specific contract address and then save only the specific storage slots you filtered?

**Comment by shekhirin** [comment]
@alessandromazza98 great! I assigned you.

> you mean filtering both with a specific contract address and then save only the specific storage slots you filtered?

Yes, that's right. We need to have both option to save all storage changes related to specific contract, and save only the changes related to specific contract + its storage slot(s).

See how logs filtering configuration works now: https://paradigmxyz.github.io/reth/run/config.html#example-of-the-custom-pruning-configuration, I think we want granular storage history pruning behave in a similar way, so something like this:
```toml
# Prune all storage history entries, leaving only those that belong to:
# - Contract `0x7ea2be2df7ba6e54b1a9c70676f668455e329d29`, starting from the block 15000000
# - Contract `0x7ea2be2df7ba6e54b1a9c70676f668455e329d29` and its storage slot `0x517586d1d6aba629182cbaba4171a955c27c86f2859f2b735993a00af12e70a0`, starting from the block 17000000
# - Contract `0xdac17f958d2ee523a2206206994597c13d831ec7` in the last 1001 blocks
[prune.parts.storage_history_filter]
"0x7ea2be2df7ba6e54b1a9c70676f668455e329d29" = { before = 15000000 }
"0x7ea2be2df7ba6e54b1a9c70676f668455e329d29".slots."0x517586d1d6aba629182cbaba4171a955c27c86f2859f2b735993a00af12e70a0" = { before = 17000000 }
"0xdac17f958d2ee523a2206206994597c13d831ec7" = { distance = 1000 }
```

I _think_ this is a legit TOML syntax.
