### ISSUE TITLE
Lock `git` dependency to a revision in Cargo.toml

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4537]
### Describe the bug

Currently, importing any crate using a tag like `v0.1.0-alpha.8` fails to build because of breaking changes in `c-kzg`.

See TG discussion starting from: <https://t.me/paradigm_reth/14004>

### Steps to reproduce

New Cargo project with

```toml
[dependencies]
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v0.1.0-alpha.8" }
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct
