### ISSUE TITLE
Database error on IndexStorageHistory step on block 7.600.000: Failed to read a value from a database table (-30796) 

### ISSUE THREAD

**Issue by Valadaress** [paradigmxyz/reth#6158]
### Describe the bug

I'm syncing an archive node on windows using docker and wls, it was syncing normaly since reach the block 7.600.000. Since it happen the reth node restart about 10 to 10 minutes.
![imagem_2024-01-22_110408393](https://github.com/paradigmxyz/reth/assets/57867475/fe63ba96-b032-4374-8e3a-d0531e93931c)
![imagem_2024-01-22_110428049](https://github.com/paradigmxyz/reth/assets/57867475/4bac0d73-3cb6-4681-8991-f496cd974df5)

## Steps to reproduce:

01 - Download Docker
02 - Clone GitHub repository
03 - Changed the DockerCompose.yml and LightHouse.yml file to store the DB direct in SSD folder and not in volumes
04 - Changed the DockerCompose.yml and LightHouse.yml file to enable `txpool` function and WebSocket port
05 - build docker image and run the containers
06 - Follow the steps bellow to increase the 1TB storage cap from WSL [here](https://learn.microsoft.com/en-us/windows/wsl/disk-space#how-to-expand-the-size-of-your-wsl-2-virtual-hard-disk)
07 - Just Wait to sync on 0.1.0-alpha.13 version
08 - The Error occurred
09 - Updated to 0.1.0-alpha.15
10 - The error persists

### Docker Compose File:

```yml
version: '3.9'
name: 'reth'

services:
  reth:
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth
    ports:
      - '9001:9001' # metrics
      - '30303:30303' # eth/66 peering
      - '8545:8545' # rpc
      - '8546:8546' # ws
      - '8551:8551' # engine
    volumes:
      - F:\db\rethdata_mainnet:/root/.local/share/reth/mainnet/db
      - F:\db\rethdata_sepolia:/root/.local/share/reth/sepolia/db
      - F:\db\rethlogs:/root/rethlogs
      - ./jwttoken:/root/jwt:ro
    # For Sepolia, replace `--chain mainnet` with `--chain sepolia`
    command: >
      node
      --chain mainnet
      --metrics 0.0.0.0:9001
      --log.file.directory /root/rethlogs
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /root/jwt/jwt.hex
      --http --http.addr 0.0.0.0 --http.port 8545
      --ws --ws.addr 0.0.0.0 --ws.port 8546
      --http.api "eth,net,web3,txpool"
      --ws.api "eth,net,web3,txpool"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    depends_on:
      - reth
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - F:\db\prometheusdata:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.1.0
    depends_on:
      - reth
      - prometheus
    ports:
      - 3000:3000
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    volumes:
      - F:\db\grafanadata:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning_temp/dashboards
    # 1. Copy dashboards from temp directory to prevent modifying original host files
    # 2. Replace Prometheus datasource placeholder with the actual name
    # 3. Run Grafana
    entrypoint: >
      sh -c "cp -r /etc/grafana/provisioning_temp/dashboards/. /etc/grafana/provisioning/dashboards &&
             find /etc/grafana/provisioning/dashboards/ -name '*.json' -exec sed -i 's/$${DS_PROMETHEUS}/Prometheus/g' {} \+ &&
             /run.sh"
    
# volumes:
#   rethdata_mainnet:
#     driver: local
#   rethdata_sepolia:
#     driver: local
#   rethlogs:
#     driver: local
#   prometheusdata:
#     driver: local
#   grafanadata:
#     driver: local
```

### LightHouse File:
```yml
version: '3.9'
name: reth

services:
  lighthouse:
    restart: unless-stopped
    image: sigp/lighthouse
    depends_on:
      - reth
    ports:
      - '5052:5052/tcp' # rpc
      - '5053:5053/tcp'
      - '5054:5054/tcp' # metrics
      - '9000:9000/tcp' # p2p
      - '9000:9000/udp' # p2p
    volumes:
      - F:\db\lighthousedata:/root/.lighthouse
      - ./jwttoken:/root/jwt:ro
    # For Sepolia:
    # - Replace `--network mainnet` with `--network sepolia`
    # - Use different checkpoint sync URL: `--checkpoint-sync-url https://sepolia.checkpoint-sync.ethpandaops.io`
    command: >
      lighthouse bn
      --network mainnet
      --http --http-address 0.0.0.0
      --execution-endpoint http://reth:8551
      --metrics --metrics-address 0.0.0.0
      --execution-jwt /root/jwt/jwt.hex
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io

  metrics-exporter:
    restart: unless-stopped
    image: ethpandaops/ethereum-metrics-exporter:debian-latest
    depends_on:
      - reth
      - lighthouse
    ports:
      - 9091:9091 # metrics
    volumes:
      - ./ethereum-metrics-exporter/config.yaml:/root/config.yaml
    command:
      - --config=/root/config.yaml
      - --metrics-port=9091

# volumes:
#   lighthousedata:
#     driver: local
```

### Platform(s)

Windows (x86) + Docker

### What version/commit are you on?

Build on: 0.1.0-alpha.13 - Current on: 0.1.0-alpha.15

### What database version are you on?

reth db version
Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

The command is in .yml file provided in Steps to reproduce step

### Code of Conduct

- [X] I agree to follow the Code of Conduct
