### ISSUE TITLE
Low CPU utilization during SenderRecovery on ARM Ampere

### ISSUE THREAD

**Issue by 0xAlcibiades** [paradigmxyz/reth#7022]
### Describe the bug

I'm seeing something like 3-4 cores utilized during SenderRecovery, rather than 64 available. The node is about 1% iowait, but otherwise 70% idle.

### Steps to reproduce

Run reth on ampere arm architecture

### Platform(s)

Linux (ARM)

### What version/commit are you on?

alpha 21

### What database version are you on?

alpha 21

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Can you provide more info about your environment? It would be great to know:
* is reth running in a container or VM? If so, how is it provisioned or limited
* if in k8s, the requests and limits set, and any container cgroups

**Comment by 0xAlcibiades** [comment]
container, 128gb limit/requests, 32 cpu limit/requests, node @ 12% utilization (64 core/256gb ram), ARM so no cgroups, everything full bore.

**Comment by Rjected** [comment]
Also, if it's possible, do you mind trying a testnet instance outside of the container setup, and letting us know whether or not that utilizes cores properly during sender recovery?

**Comment by 0xAlcibiades** [comment]
Hah, my bad, I was thinking about c-states/intel power states. But it's just running as a regular container in kubernetes, and nowhere near limits/reservations. I could give that a shot, yes.

```
rpcService:
  name: reth-mainnet-archive
  goerli: false
  image:
    repository: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.21
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: "32"
      memory: "128000Mi"
    requests:
      cpu: "32"
      memory: "128000Mi"
  volume:
    capacity: 8000Gi
    storageClass: "ceph-block"
   ```

Nothing particular going on with container cpu priority here, and overall CPU on the node is 70% idle. I can try running it outside of the container if that'd be helpful.
